FROM node:18-alpine

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy ONLY root workspace config
COPY package.json pnpm-workspace.yaml ./


# Copy ONLY this service's package.json (not allservices)
COPY services/activity-service/package.json ./services/activity-service/package.json




# Install ONLY this service's dependencies
RUN pnpm install --filter activity-service --shamefully-hoist




# Copy ONLY this service's source
COPY services/activity-service ./services/activity-service/




WORKDIR /app/services/activity-service




EXPOSE 4007




CMD ["../../node_modules/.bin/ts-node-dev", "--respawn", "--transpile-only", "--exit-child","src/index.ts"]

