FROM node:18-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml  ./

COPY services/review-and-feedback/package.json ./services/review-and-feedback/


COPY services/shared/package.json ./services/shared/

# Install with --shamefully-flatten to completely avoid symlinks

RUN npm install -g pnpm && \
    pnpm install --shamefully-hoist 
 
# COPY /app/node_modules ./node_modules
     
 COPY services/review-and-feedback ./services/review-and-feedback/

WORKDIR /app/services/review-and-feedback


EXPOSE 4002

CMD ["/app/node_modules/ts-node-dev/lib/bin.js", "--respawn", "src/index.ts"]