FROM node:18-alpine




WORKDIR /app




# Install pnpm
RUN npm install -g pnpm




# Copy ONLY root workspace config
COPY package.json pnpm-workspace.yaml ./




# Copy ONLY this service's package.json (not allservices)
COPY services/review-and-feedback/package.json ./services/review-and-feedback/package.json




# Install ONLY this service's dependencies
RUN pnpm install --filter review-and-feedback --shamefully-hoist




# Copy ONLY this service's source
COPY services/review-and-feedback ./services/review-and-feedback/




WORKDIR /app/services/review-and-feedback




EXPOSE 4002




CMD ["../../node_modules/.bin/ts-node-dev", "--respawn", "--transpile-only", "--exit-child","src/index.ts"]

