version: "3.8"
services:
  user-management:
    build:
      context: ../..
      dockerfile: services/user-management/Dockerfile.dev
    ports:
      - "3001:4000"
    volumes:
      - ./src:/app/services/user-management/src
      - ../shared:/app/services/shared
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
