services:
  - type: web
    name: user-management
    env: docker
    repo: https://github.com/Colauncha/Fixserv.git
    region: oregon
    plan: free
    dockerfilePath: ./services/user-management/Dockerfile
    buildFilter:
      paths:
        - services/user-management/**
    envVars:
      - key: MONGO_URI
        fromSecret: mongodb-secret
      - key: JWT_KEY
        fromSecret: jwt-secret
    autoDeploy: true

  - type: web
    name: service-management
    env: docker
    repo: https://github.com/Colauncha/Fixserv.git
    region: oregon
    plan: free
    dockerfilePath: ./services/service-management/Dockerfile
    buildFilter:
      paths:
        - services/service-management/**
    envVars:
      - key: MONGO_URI
        fromSecret: mongodb-secret
      - key: JWT_KEY
        fromSecret: jwt-secret
    autoDeploy: true

  - type: web
    name: review-and-feedback
    env: docker
    repo: https://github.com/Colauncha/Fixserv.git
    region: oregon
    plan: free
    dockerfilePath: ./services/review-and-feedback/Dockerfile
    buildFilter:
      paths:
        - services/review-and-feedback/**
    envVars:
      - key: MONGO_URI
        fromSecret: mongodb-secret
      - key: JWT_KEY
        fromSecret: jwt-secret
    autoDeploy: true

  - type: background
    name: redis
    env: docker
    repo: https://github.com/Colauncha/Fixserv.git
    dockerfilePath: ./services/infra/redis/Dockerfile
    buildCommand: ""
    startCommand: "redis-server"
    autoDeploy: true
