apiVersion: skaffold/v3
kind: Config
deploy:
  kubectl:
    manifests:
      paths:
        - ./services/infra/k8s/*
build:
  local:
    push: false
  tagPolicy:
    customTemplate:
      template: "{{.IMAGE_NAME}}:1.0.0"
  artifacts:
    - image: docker.io/ogkpos/user-management
      context: .
      docker:
        dockerfile: services/user-management/Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
