apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./services/infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: israel/user-management
      context: .
      docker:
        dockerfile: services/user-management/Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: israel/service-management
      context: .
      docker:
        dockerfile: services/service-management/Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: israel/review-and-feedback
      context: .
      docker:
        dockerfile: services/review-and-feedback/Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
