apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./services/infra/k8s/*
      # - ./services/infra/k8s/user-management-depl.yaml
      # - ./services/infra/k8s/service-management-depl.yaml
      # - ./services/infra/k8s/order-management-depl.yaml
      # - ./services/infra/k8s/ingress-srv.yaml
      # - ./services/infra/k8s/mongo-secret.yaml
      # - ./services/infra/k8s/jwt-secret.yaml
build:
  local:
    push: false
    concurrency: 2
  artifacts:
    - image: docker.io/ogkpos/user-management
      context: .
      docker:
        dockerfile: services/user-management/Dockerfile.dev
      sync:
        manual:
          - src: "services/user-management/src/**/*.ts"
            dest: /app/services/user-management/src

    - image: docker.io/ogkpos/service-management
      context: .
      docker:
        dockerfile: services/service-management/Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: docker.io/ogkpos/review-and-feedback
      context: .
      docker:
        dockerfile: services/review-and-feedback/Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: docker.io/ogkpos/search-and-discovery
      context: .
      docker:
        dockerfile: services/search-and-discovery/Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: docker.io/ogkpos/order-management
      context: .
      docker:
        dockerfile: services/order-management/Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: docker.io/ogkpos/wallet-service
      context: .
      docker:
        dockerfile: services/wallet-service/Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: docker.io/ogkpos/notifications-service
      context: .
      docker:
        dockerfile: services/notifications-service/Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

profiles:
  - name: user-only
    build:
      local:
        push: false
      artifacts:
        - image: docker.io/ogkpos/user-management
          context: .
          docker:
            dockerfile: services/user-management/Dockerfile.dev
          sync:
            manual:
              - src: "services/user-management/src/**/*.ts"
                dest: /app/services/user-management/src

  - name: service-only
    build:
      local:
        push: false
      artifacts:
        - image: docker.io/ogkpos/service-management
          context: .
          docker:
            dockerfile: services/service-management/Dockerfile.dev
          sync:
            manual:
              - src: "services/service-management/src/**/*.ts"
                dest: /app/services/service-management/src

  - name: core
    build:
      local:
        push: false
        concurrency: 2
      artifacts:
        - image: docker.io/ogkpos/user-management
          context: .
          docker:
            dockerfile: services/user-management/Dockerfile.dev
          sync:
            manual:
              - src: "services/user-management/src/**/*.ts"
                dest: /app/services/user-management/src
        - image: docker.io/ogkpos/service-management
          context: .
          docker:
            dockerfile: services/service-management/Dockerfile.dev
          sync:
            manual:
              - src: "services/service-management/src/**/*.ts"
                dest: /app/services/service-management/src
        - image: docker.io/ogkpos/order-management
          context: .
          docker:
            dockerfile: services/order-management/Dockerfile.dev
          sync:
            manual:
              - src: "services/order-management/src/**/*.ts"
                dest: /app/services/order-management/src
