apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./services/infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: israel/user-service
      context: services/user-management
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
