FROM node:18-alpine




WORKDIR /app




# Install pnpm
RUN npm install -g pnpm




# Copy ONLY root workspace config
COPY package.json pnpm-workspace.yaml ./




# Copy ONLY this service's package.json (not allservices)
COPY services/notifications-service/package.json ./services/notifications-service/package.json




# Install ONLY this service's dependencies
RUN pnpm install --filter notifications-service --shamefully-hoist




# Copy ONLY this service's source
COPY services/notifications-service ./services/notifications-service/




WORKDIR /app/services/notifications-service




EXPOSE 4006




CMD ["../../node_modules/.bin/ts-node-dev", "--respawn", "--transpile-only", "--exit-child","src/index.ts"]

