apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: fixserv.dev
      http:
        paths:
          - path: /api/admin
            pathType: Prefix
            backend:
              service:
                name: user-service-srv
                port:
                  number: 4000
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: user-service-srv
                port:
                  number: 4000
