apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-and-feedback-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-and-feedback
  template:
    metadata:
      labels:
        app: review-and-feedback
    spec:
      containers:
        - name: review-and-feedback
          image: docker.io/ogkpos/review-and-feedback
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          ports:
            - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: review-and-feedback-srv
spec:
  selector:
    app: review-and-feedback
  ports:
    - name: review-and-feedback
      protocol: TCP
      port: 4002
      targetPort: 4002
