apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-management-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-management
  template:
    metadata:
      labels:
        app: service-management
    spec:
      containers:
        - name: service-management
          image: docker.io/ogkpos/service-management:1.0.0
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          ports:
            - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: service-management-srv
spec:
  selector:
    app: service-management
  ports:
    - name: service-management
      protocol: TCP
      port: 4001
      targetPort: 4001
