# Generated by Django 5.1.3 on 2024-12-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Television', 'Television'), ('Refrigerator', 'Refrigerator'), ('Gadgets', 'Gadgets'), ('Game Gadgets', 'Game Gadgets')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='artisans/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
