FROM node:18-alpine


WORKDIR /app


# Install pnpm
RUN npm install -g pnpm


# Copy ONLY root workspace config
COPY package.json pnpm-workspace.yaml ./


# Copy ONLY this service's package.json (not all services)
COPY services/order-management/package.json ./services/order-management/package.json


# Install ONLY this service's dependencies
RUN pnpm install --filter order-management --shamefully-hoist


# Copy ONLY this service's source
COPY services/order-management ./services/order-management/


WORKDIR /app/services/order-management


EXPOSE 4004


CMD ["../../node_modules/.bin/ts-node-dev", "--respawn", "--transpile-only", "--exit-child", "src/index.ts"]