name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main
      - build
    paths-ignore:
      - 'README.md'
  
jobs:
  build-and-push:
    name: Build and Push ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        service:
          - user-management
          - order-management
          - service-management
          - notifications-service
          - wallet-service
          - search-and-discovery
          - review-and-feedback

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. (Optional but Recommended) Generate image tags automatically
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/fixserv-${{ matrix.service }}

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build, push, and cache the image in one step
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./services/${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # Use tags generated by metadata-action
          labels: ${{ steps.meta.outputs.labels }}
          build-args: | # Pass build arguments
            NODE_ENV=production
          cache-from: type=gha # Enable caching from GitHub Actions cache
          cache-to: type=gha,mode=max # Enable caching to GitHub Actions cache